from datetime import date, datetime, timezone

from loguru import logger
from sqlalchemy import create_engine, text

from app.config import DB_URL

engine = None

if DB_URL:
    try:
        engine = create_engine(DB_URL)
    except Exception:
        logger.exception(f"Invalid DB_URL format. Length of DB_URL: {len(DB_URL)}")
        engine = None
else:
    logger.warning("DB_URL is not set. Database features will be disabled.")


def create_table() -> None:
    if engine is None:
        logger.warning("Database not configured, skipping table creation.")
        return

    sql_create = text("""
        CREATE TABLE IF NOT EXISTS garch_preds (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            ticker VARCHAR(10) NOT NULL,
            execution_time TIMESTAMP DEFAULT NOW(),
            target_date DATE NOT NULL,
            p INTEGER NOT NULL,
            q INTEGER NOT NULL,
            dist VARCHAR(15) NOT NULL,
            prediction FLOAT NOT NULL,
            CONSTRAINT unique_pred UNIQUE (ticker, target_date, p, q, dist)
        );
    """)
    with engine.begin() as conn:
        conn.execute(sql_create)
        logger.info("Succesfully created table 'garch_preds' or table exists")


def store_preds(ticker: str, pred: float, target_date: date, params: dict) -> None:
    if engine is None:
        logger.info(f"Skipping DB save for {ticker} (DB not configured)")
        return

    execution_time = datetime.now(timezone.utc)
    pred = pred.item() if hasattr(pred, "item") else float(pred)

    sql_insert = text("""
        INSERT INTO garch_preds (ticker, target_date, prediction, execution_time, p, q, dist)
        VALUES (:ticker, :target_date, :prediction, :execution_time, :p, :q, :dist)
        ON CONFLICT (ticker, target_date, p, q, dist) 
        DO UPDATE SET 
            prediction = EXCLUDED.prediction,
            execution_time = EXCLUDED.execution_time;
    """)
    with engine.begin() as conn:
        conn.execute(
            sql_insert,
            {
                "ticker": ticker,
                "target_date": target_date,
                "execution_time": execution_time,
                "p": params["p"],
                "q": params["q"],
                "dist": params["dist"],
                "prediction": pred,
            },
        )
        logger.info(f"Stored prediction for {ticker} (Target: {target_date})")
